### ISSUE TITLE
White BAckground boxes very annoying, please can you have option of transparent

### ISSUE THREAD

**Issue by amityweb** [oraz/bookmarksMenu#18]
The white background behind  the boxes that pop up is very annoying to the point I may not use the extension. Shame because the rest of it is great. If I try to enter transparent, or none, or blank in the background colour it reverts back to the previous colour. So it wont allow me to try these options. 

please can you either give us the option to set a none, transparent or blank colour, or remove this effect all together? And any border? So no background box is visible. There is no need to see this. 

If a box is needed for it to work, just make it invisible. Then it will be perfect. 

Thanks

**Comment by Scoubi-7** [comment]
There is still no solution ?
It's a shame because without this problem for me it would be the best extension that manages bookmarks

**Comment by oraz** [comment]
Unfortunately no.
The popup must be always presented, and it's impossible to make it transparent.

**Comment by Scoubi-7** [comment]
Too sad
