### ISSUE TITLE
"Already bookmarked" indicator for Google mode

### ISSUE THREAD

**Issue by ekipan** [oraz/bookmarksMenu#2]
If one is viewing a page that's already in one's Chrome bookmarks, the address bar "Bookmark this page" button turns yellow.

An analogous feature could be useful for the Bookmarks Menu extension when it's in Google bookmarks mode. Perhaps changing the green "G" overlay to red for example. Preferably it would be something more obvious. :)

**Comment by oraz** [comment]
Google bookmarks are not supported any more because GoogleBookmarks service is dead since 2021
